project:
  type: website
  output-dir: docs

website:
  title: "4MA1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked      # or "floating"
    contents: auto     # auto-generates from headers
    title: "Contents"
    pinned: true       # keeps sidebar always visible


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


