project:
  type: website
  output-dir: docs

website:
  title: "4MA1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    pinned: true
    title: "Contents"
    contents:
      - index.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
