project:
  type: website
  output-dir: docs

website:
  title: "4MA1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    sidebar:
      style: "floating"  # or "docked"
      contents: auto


