project:
  type: website
  output-dir: docs

website:
  title: "4MA1"
  sidebar:
    title: "Contents"
    style: docked
    pinned: true
    contents:
      - href: index.qmd
        text: Home
      - href: vectors.qmd
        text: Vectors

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
