---
title: "Scheme of Work"
---

::: {.raw-html}

<table>
  <thead>
    <tr>
      <th style="width:10%; vertical-align: top;">Topic Code</th>
      <th style="width:10%; vertical-align: top;">Duration</th>
      <th style="width:80%; vertical-align: top;">Content</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>N2</td>
      <td>2wk</td>
      <td>Ratio and percentages * Percentages definition, forward and backward calculation * Significant figures and rounding (recap when required in questions) * Compound interest and repeated percentage changes * Ratio of two and three quantities (including algebra problems)</td>
    </tr>
    <tr>
      <td>G2</td>
      <td>1wk</td>
      <td>Transformation - Can use tracing paper * Translation (using column vectors) * Reflection (about y=a, x=b, y=x and y=-x only) * Rotation (90, 180, 270 degrees) * Enlargement (+ve scale factor only, incl. scale factor between 0 and 1) * Successive transformations</td>
    </tr>
    <tr>
      <td>G3</td>
      <td>2wk</td>
      <td>Similar shapes: triangles * Identifying similar triangles by AA (with and without parallel lines) * Length and area ratios of similar triangles and other similar 2D shapes * Algebra problems</td>
    </tr>
    <tr>
      <td>G4</td>
      <td>2.5wk</td>
      <td>Trigonometry * Pythagoras theorem and its converse * tan and arctan * sin & cos and their inverses * Compound right-angled triangles (No bearings or angles of elevation/depression)</td>
    </tr>
    <tr>
      <td>S2</td>
      <td>2wk</td>
      <td>Probability * Probability calculation using symmetry * Mutually exclusive and independent events ("not", "or", "and" rules) * Probability tree, incl. selection problems with and without replacement</td>
    </tr>
    <tr>
      <td>E</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>A3</td>
      <td>2.5wk</td>
      <td>Graph basics: * Graph of y=mx+c and calculation of m from a given graph; Interpretation of m, c and the x-intercept (no equation of the line algebra, but incl. relations of y=mx+c, y=-mx+c and y=-mx-c); to include examples using other letters, e.g. v=u+at, where u and a are constants * Plot (quadratic, cubic, reciprocal) curves using table of values, incl. table of values on a calculator</td>
    </tr>
    <tr>
      <td>G5</td>
      <td>3.5wk</td>
      <td>Perimeter, Area and Volume * Area of: rectangle, parallelogram, triangle (no (1/2)ab*sinC), trapezium * Circles: perimeter and area of a circle; arc-length and area of a sector (no segment) * Surface area and volume of 3D shapes: cuboid, prism, cylinder * Compound shapes and shapes subtraction * Unit conversion * Algebra problems (No similar objects)</td>
    </tr>
    <tr>
      <td>S1</td>
      <td>0.5wk</td>
      <td>Descriptive statistics * Mean, median, mode, range for ungrouped data only, incl. frequency table and algebra problems</td>
    </tr>
    <tr>
      <td>R</td>
      <td>1wk</td>
      <td>Revise for Novi End of Year Exam</td>
    </tr>
    <tr>
      <td>ST</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>nan</td>
      <td>nan</td>
      <td>2M45678</td>
    </tr>
    <tr>
      <td>F</td>
      <td>1.5wk</td>
      <td>Further Algebra * Novi algebra recap: expanding brackets, solving linear equations and simultaneous equations, re-arranging formulae * Expanding three brackets [Book reference: A7] * Harder re-arrangement: unknown in two places (excl. algebraic fractions and surds) [Book reference: A7]</td>
    </tr>
    <tr>
      <td>N3</td>
      <td>1wk</td>
      <td>Arithmetic progression * Sequence notation, position-to-term and recursive rules * AP: finding the n-th term (incl. inverse problems, e.g. how many terms are between 100 and 1000)</td>
    </tr>
    <tr>
      <td>A6</td>
      <td>2.5wk</td>
      <td>Coordinate geometry: * Quadrants * Points: mid-point, distance, reflection about veritcal/horizontal lines and y=x * Equation of a line: all forms * Multiple lines: parallel lines, perpendicular lines, triangles, parallelograms and squares * Simultaneous equations and point of intersection * Problem solving (contents may vary by sets): e.g. point-line distance (default method: perpendicular line -> point of intersection -> distance), area problems * Shading regions defined by 2D inequalities</td>
    </tr>
    <tr>
      <td>A4A7</td>
      <td>3.5wk</td>
      <td>Factorising and solving quadratics (Factorisable quadratics only) * Common factors * Difference of squares (incl. 75x^2 - 12 type) * General quadratic factorisation: cross method or splitting the middle term * Solving quadratics using factorisation * Linear+quadratic simultaneous equations (restricted to factorisable quadratics) * Solving equations with algebraic fractions (eliminating the denominator) * Algebraic fractions * Harder re-arrangement: with algebraic fractions  ⌂ The last two bullet points may not be included in the Exam depending on the Yr2 timetable</td>
    </tr>
    <tr>
      <td>R</td>
      <td>1wk</td>
      <td>Revise for a test on this term's work (incl. revision topics from Novi)</td>
    </tr>
    <tr>
      <td>MT</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>A9</td>
      <td>1wk</td>
      <td>Proportionality * Direct and inverse proportion, incl powers (x^2 is proportional to y^3) * Graphical representation (y=kx and y=k/x for positive k and x)</td>
    </tr>
    <tr>
      <td>E</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>A5</td>
      <td>2.5wk</td>
      <td>Indices and Surds (NB ±√x ≠ √x)  * Indices laws: Derivation/Connection between the laws * Standard form * Fractional indices * Surds algebra  * Re-arrangement with exponents and surds [Book reference: A7] * Algebraic standard form (may include exponents and surds)</td>
    </tr>
    <tr>
      <td>A8</td>
      <td>3wk</td>
      <td>Quadratic curve * Completing the square and its use in solving quadratic equations, deriving the quadratic formula, finding the axis of symmetry of the curve and the coordinates of the max/min points, and curve sketching * Use of the quadratic formula * Quadratic inequality and solution on the number line * Worded quadratic problems (present both roots and give clear reason for rejection)</td>
    </tr>
    <tr>
      <td>N3</td>
      <td>1wk</td>
      <td>AP(ii) * AP(i) recap: finding the n-th term * Sum of AP and algebra problems (e.g. finding the number of terms that add up to a given sum)</td>
    </tr>
    <tr>
      <td>S3</td>
      <td>2.5wk</td>
      <td>Process data * Mode/modal class, median, mean, mid-range, range in grouped data * Finding the IQR from a discrete data set * Histograms * Cumulative frequency tables * Problem solving: unknown scales * Optional projects</td>
    </tr>
    <tr>
      <td>E</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>A</td>
      <td>2wk</td>
      <td>2M45678 paper on MT and LT materials</td>
    </tr>
    <tr>
      <td>G7</td>
      <td>1wk</td>
      <td>Further trig: * SOH-CAH-TOA revision * Angles of elevation & depression * 3D trig</td>
    </tr>
    <tr>
      <td>G6</td>
      <td>2wk</td>
      <td>Circles and chords * Angle theorems (proofs are optional: not examinable in IGCSE) * Tangents theorems and the AST (proofs are optional) * Chords perpendicular to a diameter * Intersecting chords (incl. algebra problems involving quadratic equations)</td>
    </tr>
    <tr>
      <td>G3</td>
      <td>2.5wk</td>
      <td>PAV: * Similar 3D objects and volume (mass), area (paint) and length ratios * Surface area and volume of 3D shapes: pyramid (simple base only for surfae area), cone, sphere and frustum * Algebra problems and problem solving</td>
    </tr>
    <tr>
      <td>N4</td>
      <td>0.5wk</td>
      <td>Bounds incl. harder examples such as x/(y+z) and x/(y-z) etc -  may vary contents by sets</td>
    </tr>
    <tr>
      <td>ST</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>nan</td>
      <td>nan</td>
      <td>3M345678</td>
    </tr>
    <tr>
      <td>G8</td>
      <td>1.5wk</td>
      <td>Circular functions * Graphs of sin, cos and tan for any angle * Sine equations: sin(x)=0.6 type only, 0&lt;x&lt;180 degrees * Area of triangle = (1/2)ab*sin(C) and its application in finding the area of a segment * Sine and cosine rules * 3 figure bearings</td>
    </tr>
    <tr>
      <td>A10</td>
      <td>1wk</td>
      <td>Harder graphs * Cubic and reciprocal graphs: y = ax^3 + bx^2 + cx + d + e/x + f/x^2, where at least three coefficients are 0 * Solving from graphs, incl. curve = line with re-arrangement and manipulation * Estimating gradient</td>
    </tr>
    <tr>
      <td>A11</td>
      <td>2wk</td>
      <td>Differentiation * Differentiating x^n, where n=-2, -1, 0, 1, … * Finding gradients, rates of change * Equation of the tangent at a given point (for 3M345 only; not spelt out in IGCSE specification, but likely to appear soon) * Stationary points: determine max/min using knowledge of the shape of quadratic and cubic curves (first derivatives test not required) * Kinematics application and other applications, incl. setting up an objective function to maximise/minimise</td>
    </tr>
    <tr>
      <td>N6</td>
      <td>1.5wk</td>
      <td>Sets * Set builder notation and interval notation * Union, intersection, belongs to, not belonging to, subset, complement, universal set, empty set, set cardinality * Venn diagrams: shading regions (incl. 3 circles) and probability problems * 3 circles problems (without inclusion-exclusion principle for 3 sets), incl. use of algebra * N⊂Z⊂Q⊂R⊂C, and Z^+, R^+, R\Q notations. The concept of irrational numbers (no proofs required)</td>
    </tr>
    <tr>
      <td>N7</td>
      <td>1.5wk</td>
      <td>Harder Numbers and Numbers proofs * Recurring decimals and conversion to fractions * Harder HCF and LCM questions * IGCSE Numbers proofs using algebra * Unit conversion (incl. compound measures), e.g. km/h to m/s</td>
    </tr>
    <tr>
      <td>A</td>
      <td>2wk</td>
      <td>GCSE Algebra review (by techniques, mix topics) * Booklet 1: Linear equations; Inequalities; Re-arranging equations; Expanding brackets; Indices laws; Standard form * Booklet 2: Factorisation; Solving quadratic equations; Quadratic inequality; Simultaneous equations; Fractions; Algebraic fractions; Surds</td>
    </tr>
    <tr>
      <td>MT</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>P</td>
      <td>2wk</td>
      <td>GCSE Algebra review (by techniques, mix topics) * Booklet 3: Coordinate geometry; Quadratic graph; Completing the square; Solving from graph; Calculus  1 pair of past papers for mock revision; 1 pair for Christmas holiday</td>
    </tr>
    <tr>
      <td>E</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>M</td>
      <td>2wk</td>
      <td>GCSE Mocks and Debriefings</td>
    </tr>
    <tr>
      <td>A12</td>
      <td>1.5wk</td>
      <td>Functions * Notation * Domain and range, incl. restricted domain * Composite function * Inverse function and graphs</td>
    </tr>
    <tr>
      <td>G9</td>
      <td>1.5wk</td>
      <td>Vectors * Notation and algebra * Parallel and collinearity proofs</td>
    </tr>
    <tr>
      <td>A13</td>
      <td>1wk</td>
      <td>Function transformation * Translation: equation <-> graph * Stretch: equation <-> graph * Successive transformation (both directions: function <-> graph) for linear, quadratic, sine and cosine functions</td>
    </tr>
    <tr>
      <td>G</td>
      <td>2wk</td>
      <td>GCSE Geometry review (by techniques, mix topics) * Booklet 1: Angle chase * Booklet 2: Sides (trig, sine and cosine rules, isosceles triangles) * Booklet 3: Similarity, PAV, shape transformations * Compass construction of angle bisector and perpendicular bisector of a line segment [Not covered before]</td>
    </tr>
    <tr>
      <td>A</td>
      <td>0.5wk</td>
      <td>GCSE Algebra review (by techniques, mix topics) * Booklet 4: Word problems (incl. ratio, percentage, proportional reasoning and anything involving setting up equations)</td>
    </tr>
    <tr>
      <td>P</td>
      <td>1wk</td>
      <td>Two pairs of papers during lessons and Easter holidays</td>
    </tr>
    <tr>
      <td>E</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>B</td>
      <td>nan</td>
      <td>nan</td>
    </tr>
    <tr>
      <td>P</td>
      <td>3wk</td>
      <td>4 pairs of past papers</td>
    </tr>
  </tbody>
</table>

:::